### ISSUE TITLE
[Feat] Navbar 개발

### ISSUE THREAD

**Issue by JJangYunji** [all-solved/FE#10]
## 🛠 Issue

- [ ] 사이드 Navbar 개발하기

## 📝 To-do

- [ ] Navbar component 작성
- [ ] Navbar css 작성
- [ ] Navbar Navlink 작성

**Comment by JJangYunji** [comment]
Navbar 항목에 Navlink 추가
