### ISSUE TITLE
[Fix] Navbar,header 스타일 변경

### ISSUE THREAD

**Issue by ljh0608** [all-solved/FE#26]
## 🛠 Issue
- header에 아이콘 삽입 
- navbar 메인 아이콘 변경
- header title 삽입
## 📝 To-do

- [ ] header에 아이콘 삽입 
- [ ]  navbar 메인 아이콘 변경
- [ ] header title 삽입
